export enum LeaveTypeEmployeeLeave{

  CONTRIBUTORS_DEATH = 'CONTRIBUTORS_DEATH',
  MATERNITY_LEAVE = 'MATERNITY_LEAVE',
  PATERNITY_LEAVE = 'PATERNITY_LEAVE',
  WORK_INJURY = 'WORK_INJURY',
  VACATION = 'VACATION',
  TERMINATION = 'TERMINATION',
  OTHERS = 'OTHERS',

}
